# RabbitMQ Secret untuk Message Broker Credentials
# Author: Latifa Keysha (2311083019) - TRPL 3C
# Sesuai dengan panduan PDF: Tahap 3 - Secrets Configuration
#
# Default RabbitMQ credentials:
# Username: guest (base64: Z3Vlc3Q=)
# Password: guest (base64: Z3Vlc3Q=)

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: perpustakaan-ns
type: Opaque
data:
  rabbitmq-username: Z3Vlc3Q=
  rabbitmq-password: Z3Vlc3Q=
