# Deploy All Services - Perpustakaan Microservices
# Urutan deployment: Namespace -> Infrastructure (RabbitMQ, Eureka) -> Services

---
# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: perpustakaan-ns

---
# 2. RabbitMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: perpustakaan-ns
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP

---
# 3. Eureka Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-container
          image: perpustakaan/eureka-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: perpustakaan-ns
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP

---
# 4. API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: perpustakaan/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
# 5. Anggota Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anggota-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anggota-service
  template:
    metadata:
      labels:
        app: anggota-service
    spec:
      containers:
        - name: anggota-container
          image: perpustakaan/anggota-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: anggota-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: anggota-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
# 6. Buku Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buku-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buku-service
  template:
    metadata:
      labels:
        app: buku-service
    spec:
      containers:
        - name: buku-container
          image: perpustakaan/buku-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: buku-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: buku-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
# 7. Peminjaman Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peminjaman-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peminjaman-service
  template:
    metadata:
      labels:
        app: peminjaman-service
    spec:
      containers:
        - name: peminjaman-container
          image: perpustakaan/peminjaman-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: peminjaman-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: peminjaman-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084

---
# 8. Pengembalian Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pengembalian-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pengembalian-service
  template:
    metadata:
      labels:
        app: pengembalian-service
    spec:
      containers:
        - name: pengembalian-container
          image: perpustakaan/pengembalian-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: pengembalian-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: pengembalian-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085

---
# 9. Command Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-service
  template:
    metadata:
      labels:
        app: command-service
    spec:
      containers:
        - name: command-container
          image: perpustakaan/command-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: command-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: command-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

---
# 10. Query Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-container
          image: perpustakaan/query-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087

---
# 11. RabbitMQ Peminjaman Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-peminjaman-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-peminjaman-service
  template:
    metadata:
      labels:
        app: rabbitmq-peminjaman-service
    spec:
      containers:
        - name: rabbitmq-peminjaman-container
          image: perpustakaan/rabbitmq-peminjaman-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-peminjaman-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: rabbitmq-peminjaman-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---
# 12. Rabbit Pengembalian Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-pengembalian-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-pengembalian-service
  template:
    metadata:
      labels:
        app: rabbit-pengembalian-service
    spec:
      containers:
        - name: rabbit-pengembalian-container
          image: perpustakaan/rabbit-pengembalian-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-pengembalian-service
  namespace: perpustakaan-ns
spec:
  selector:
    app: rabbit-pengembalian-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
