# kubernetes/rabbitmq-peminjaman-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-peminjaman-deployment
  namespace: perpustakaan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-peminjaman-service
  template:
    metadata:
      labels:
        app: rabbitmq-peminjaman-service
    spec:
      containers:
        - name: rabbitmq-peminjaman-container
          image: perpustakaan/rabbitmq-peminjaman-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-peminjaman-service
  namespace: perpustakaan-ns
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8086"
spec:
  selector:
    app: rabbitmq-peminjaman-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
